# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kidneyapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://kidney.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_dd5139299f7c4ae0bf2fd4252c46218c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_add825ff61834474968215c914d81027 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: kidney.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dd5139299f7c4ae0bf2fd4252c46218c }}/kidney:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kidneyapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3236e35b2ac84367b527dd60528079ba }}
        images: 'kidney.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dd5139299f7c4ae0bf2fd4252c46218c }}/kidney:${{ github.sha }}'